[project]
name = "scripts"
version = "0.1.0"
description = "Scripts for dicom-ul"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
