[package]
name = "dicom-ul-fuzz"
version = "0.0.0"
description = "Fuzz testing for the dicom-ul crate"
authors = []
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.dicom-ul]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "pdu_roundtrip"
path = "fuzz_targets/pdu_roundtrip.rs"
test = false
doc = false

[profile.release]
debug = true
